# Generated by Django 3.2 on 2021-04-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_website_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='tile',
            new_name='title',
        ),
    ]
